scan_filter_chain:
- name: box
  type: laser_filters/LaserScanBoxFilter
  params:
    box_frame: base_laser_link
    min_x: -0.1
    max_x: 0.1
    min_y: -0.1
    max_y: 0.1
    min_z: -1.0
    max_z: 1.0
